### ISSUE TITLE
Status LED without current limiting device

### ISSUE THREAD

**Issue by gnbl** [rosswesleyporter/dqmusicbox#1]
Nice project! Saw it on [Hackaday ](https://hackaday.com/2017/09/15/hackaday-prize-entry-dementia-friendly-music-player/) and came to check out the python control code and the SD write-protect.

I noticed that your "HDD LED" status indicator seems to be connected _directly_ to the Raspberry Pi GPIO.
Are these current limited outputs? It does not look like it: https://www.raspberrypi.org/documentation/usage/gpio/

So you should add a resistor or use an LED with integrated resistor that is designed for 3.3 V. Otherwise, the RPi and/or the LED could be damaged.

**Comment by rosswesleyporter** [comment]
Hi there. Thanks for checking out the project. And for taking the time to note the issue. To the best of my knowledge that is indeed an LED designed for 3.3V (originally for use on PC motherboard pins that didn't have a current limiting resistor). I spent a long time looking for an LED that is both 3.3V and pre-wired for jumper pins. Trying to make it super easy for people to build. No LED problems so far (I started building these about two years ago). But given your concern, I'll setup a test system and let it run constantly for a month.

Did you find what you were looking for regarding TMP_WRITE_PROTECT? I updated the build instructions a few weeks ago with a new appendix describing the process that I use.

**Comment by gnbl** [comment]
Ok, I don't know if HDD LEDs generally have a resistor installed or if these are on the motherboard. 
There probably is a method to test an LED for an integrated resistor.
But resistor LEDs are available (https://www.google.com/search?q=led+integrated+resistor), and then "Dupont" jumper wires could be used to connect without soldering.

Regarding the SD card: I did not know about the lock feature beforehand, though I've wondered what the Secure stands for. It's good to know, albeit as a last resort measure IMO. I've previously just tried to minimize logging to slow down the wear on the card but wanted to look into using the card as ROM and running the system from RAM alone. If I should manage to get anything working I can let you know.

**Comment by rosswesleyporter** [comment]
Just to be safe, I updated the plans to use an LED module with visible and sufficient resistors, specifically a KY-016 LED module.
