### ISSUE TITLE
dqmusicbox_v4_1 image not compatible with Raspberry Pi 3A+

### ISSUE THREAD

**Issue by scruss** [rosswesleyporter/dqmusicbox#2]
Since the 3A+ replaced the A+, the image in the instructions doesn't work. Needs an update to the firmware files in /boot from latest Raspbian

**Comment by rosswesleyporter** [comment]
Thanks for that. I think I tested with the 3A+ and it seemed to work fine. I'll check again.

**Comment by rosswesleyporter** [comment]
FYI, I just did a quick build of an image that works on a Pi 3A+. I'll do some testing with the aim to post it this weekend.

**Comment by rosswesleyporter** [comment]
Hello. I uploaded a new version of the image. Works on the Pi 3A+. Also tested on 1A+ and 3B+. And I made corresponding updates to the build instructions.  If you want to download the image: bit.ly/2UkYkl9

**Comment by scruss** [comment]
Thanks, Ross! The new image works well with my 3A+ box.

(I'm with Makers Making Change, by the way — based out of Toronto. We really appreciate what you've done with this device!)

**Comment by rosswesleyporter** [comment]
Glad to hear that it works. I love what Makers Making Change is doing. And
that reminds me that I need to update my Makers Making Change page with
info about the new model that includes speakers.
