### ISSUE TITLE
3D printed dials are at an undefined size

### ISSUE THREAD

**Issue by scruss** [rosswesleyporter/dqmusicbox#4]
![tiny_dials](https://user-images.githubusercontent.com/425706/57396456-71d0fc80-7198-11e9-9c0b-7feae826ab49.jpg)
Even after scaling by 25.4 - as might happen if you'd sized these wrongly in inches - these are tiny.

Please provide at correct scale, also perhaps rotated flat so they're easier to print.

**Comment by rosswesleyporter** [comment]
Hello again. I'll check on these when I get home i.e. remind myself how I printed it. If I remember correctly, Cura auto scaled it by some power of ten e.g. 10x, 100x, 1,000x or something. Please note that 3D printing is not my expertise. I did the laser cut design and wrote the software. Chad @ Makers Making Change found a volunteer to do the 3D design (Blender). So I'm not sure if I'll be able to correct the scaling issue. But I can update the build instructions with the amount of auto scaling that Cura applied.

**Comment by rosswesleyporter** [comment]
Hi. Confirmed - Cura autoscaled 10,000% percent for me. I didn't have to do anything. But it sounds like this is not the case for the slicer that you (and probably others) are using. So I just updated the build instructions to note that manual in-slicer scaling may be necessary. The updated instructions are now live in github and on http://DementiaMusicPlayer.org. 

If you know of a way to correct the scaling in the STL file, I'm all ears. If I recall correctly, Trey (wonderful volunteer that Chad connected to the project) tried various Blender exports but the scaling issue persisted. Also if I recall correctly, I found posts from others also puzzled by similar issues with Blender exports in some circumstances.

**Comment by jakemcivor** [comment]
I manually corrected the stl file for the dials using Autodesk Meshmixer. I also re-oriented the other files so they are in the position best suited for printing.
#5

**Comment by rosswesleyporter** [comment]
Thanks Jake! Merged.

**Comment by rosswesleyporter** [comment]
I'm assuming that everything is working for you now. So I'll close this. BTW, one of the next things I'll be working on is updating the build instructions to focus on one-sitting builds, in preparation for a likely buildathon at the Bellingham Makerspace.

**Comment by scruss** [comment]
Yes, it did, thanks; slightly loose in PET-G on Makers Making Change's
Toronto Prusa, but nothing that tape won't fix. I was going to post
these as a PR, but I see my colleague Jake beat me to it. If these were
3mf files, it would retain some of your preferred slicing settings too.
